"""Generate safe draw-time part descriptions. Dry-run by default.

Uses the original RPW only as a read-only identity/variant inventory.
Outputs JSON sources, never an RPW binary. All text fits a conservative
540-native-pixel, three-line help area at a 28px glyph quad.
"""
import argparse
import json
import re
from pathlib import Path
import rpw
from intermission_layout import ink
from parts_description_catalog import CATALOG, SOURCE

ROOT = Path(__file__).resolve().parents[1]
DESC = ROOT / 'translation/parts_descriptions.unshipped.json'
HOOK = ROOT / 'translation/parts_desc_hook.json'


def wrap(prose, mapping, widths):
    lines = ['']
    for word in prose.split():
        trial = (lines[-1] + ' ' + word).strip()
        if ink(trial, mapping, widths, 28) > 540:
            lines.append(word)
        else:
            lines[-1] = trial
    assert len(lines) <= 3, lines
    assert all(ink(line, mapping, widths, 28) <= 540 for line in lines)
    return '\n'.join(lines)


def generate(mapping, widths):
    spirits = json.loads((ROOT / 'translation/spirits.json').read_text(encoding='utf-8'))
    raw = (ROOT / 'work/orig/RPW_DATA.CPK').read_bytes()
    slots, strings = rpw.slots(raw), rpw.jstrings(raw)
    old = json.loads(DESC.read_text(encoding='utf-8'))
    result, seen = {}, set()
    for (chunk, record, col), index in slots.items():
        if chunk != 'boost-p' or record == 0 or not 3 <= col <= 8:
            continue
        name = strings[slots[chunk, record, 1]]
        seen.add(name)
        jp = strings[index]
        if jp == '－－':
            continue
        assert name in CATALOG, name
        # Spirit identities live in the authoritative spirit-name dictionary.
        prose = re.sub(r'\$\$(.*?)\$\$', lambda m: spirits[m[1]], CATALOG[name])
        if 'ＤＬ専用' in jp:
            prose += ' DLC only.'
        en = wrap(prose, mapping, widths)
        assert jp not in result or result[jp] == en, (name, jp)
        result[jp] = en
    assert seen == set(CATALOG), seen ^ set(CATALOG)
    assert set(result) == {k for k in old if not k.startswith('_')}
    return result


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--out', default='work/out_0.6.3')
    ap.add_argument('--write', action='store_true')
    args = ap.parse_args()
    out = ROOT / args.out
    mapping = json.loads((out / 'pairs.json').read_text())
    widths = {int(k): v for k, v in json.loads((out / 'widths.json').read_text()).items()}
    result = generate(mapping, widths)
    old = json.loads(DESC.read_text(encoding='utf-8'))
    changed = sum(old[jp] != en for jp, en in result.items())
    print('%d parts, %d exact description variants, %d changed; all <=3 lines / 540px.' %
          (len(CATALOG), len(result), changed))
    for fragment in ('切り払い１００', 'マップ兵器及び射程１以外の武器', '（現在のＨＰ'):
        jp = next(jp for jp in result if jp.startswith(fragment))
        print(repr(jp), '=>', repr(result[jp]))
    if args.write:
        note = ('Generated by tools/build_parts_descriptions.py from parts_description_catalog.py. '
                'Reviewed against ' + SOURCE + '. Draw-time EBOOT hooks only; NEVER replace RPW '
                'boost-p description strings (boot corruption). Historical filename retained.')
        DESC.write_bytes((json.dumps(dict(_note=note, **dict(sorted(result.items()))),
                                    ensure_ascii=False, indent=1) + '\n').encode('utf-8'))
        hook = json.loads(HOOK.read_text(encoding='utf-8'))
        hook['note'] = note
        hook['line_pairs'] = False
        hook['lines'] = [dict(jp=jp, en=en) for jp, en in sorted(result.items())]
        HOOK.write_bytes((json.dumps(hook, ensure_ascii=False, indent=1) + '\n').encode('utf-8'))


if __name__ == '__main__':
    main()
