"""Generate whole-string pilot-skill display hooks. Dry-run before --write."""
import argparse
import json
import re
from pathlib import Path
import rpw
from intermission_layout import ink
from skill_description_catalog import CATALOG, SOURCE

ROOT = Path(__file__).resolve().parents[1]
HOOK = ROOT / 'translation/skill_hook.json'


def generate(mapping,widths):
    names = {}
    for filename in ('skills.json','spirits.json'):
        names.update(json.loads((ROOT/'translation'/filename).read_text(encoding='utf-8')))
    raw = (ROOT/'work/orig/RPW_DATA.CPK').read_bytes()
    strings, slots = rpw.jstrings(raw), rpw.slots(raw)
    result, seen = {}, set()
    for (chunk,record,col),index in slots.items():
        if chunk != 'sk-pri' or not record or col not in (4,5):
            continue
        name = strings[slots[chunk,record,1]]
        seen.add(name)
        prose = re.sub(r'\$\$(.*?)\$\$',lambda m:names[m[1]],CATALOG[name])
        lines = ['']
        for word in prose.split():
            trial = (lines[-1]+' '+word).strip()
            if ink(trial,mapping,widths,28) > 740:
                lines.append(word)
            else:
                lines[-1] = trial
        assert len(lines) <= 3, (name,lines)
        en = '\n'.join(lines)
        jp = strings[index]
        assert jp not in result or result[jp] == en, (name,jp)
        result[jp] = en
    assert seen == set(CATALOG), seen ^ set(CATALOG)
    old = json.loads(HOOK.read_text(encoding='utf-8'))
    assert set(result) == {row['jp'] for row in old['lines']}
    return result


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--out',default='work/out_0.6.3')
    ap.add_argument('--write',action='store_true')
    args = ap.parse_args()
    out = ROOT/args.out
    mapping = json.loads((out/'pairs.json').read_text())
    widths = {int(k):v for k,v in json.loads((out/'widths.json').read_text()).items()}
    result = generate(mapping,widths)
    doc = json.loads(HOOK.read_text(encoding='utf-8'))
    changed = sum(row['en'] != result[row['jp']] for row in doc['lines'])
    print('%d skills; %d exact variants; %d changed. All <=3 lines / 740px at 28px.' % (len(CATALOG),len(result),changed))
    for row in doc['lines']:
        if row['jp'].startswith(('相手からの命中率','１ターンにスキルレベルと同数回、隣接','気力１３０以上でクリティカル率')):
            print(repr(result[row['jp']]))
    if args.write:
        doc['note'] = ('Generated by tools/build_skill_descriptions.py from skill_description_catalog.py; '
                       'JP skill effects reviewed against '+SOURCE+'. Existing names retained. '
                       'All sk-pri columns 4-5 variants, draw-time only; no RPW or gameplay edits. '
                       'See docs/PILOT_SKILL_DESCRIPTIONS.md for unmatched variants and reference conflicts.')
        doc['line_pairs'] = False
        doc['lines'] = [dict(jp=row['jp'],en=result[row['jp']]) for row in doc['lines']]
        HOOK.write_bytes((json.dumps(doc,ensure_ascii=False,indent=1)+'\n').encode('utf-8'))


if __name__ == '__main__':
    main()
