"""Pilot-name pieces: the fallback map for the RPW swap.

The status screens draw a pilot's name from the `pilot-nw` record as
SEPARATE strings -- w0 given name, w1 surname -- and the j-string table is
deduplicated, so ワイルダー is one pool string shared by every Wilder. A
whole-name glossary entry never matches a piece, which is why Pilot Info
showed "Jeffrey・ワイルダー" and "相良Sousuke".

The primary fix is per-slot: rpw.piece_overrides() resolves each record's
(given, surname) pair to its glossary character and gives that record's
two slots their own English, so a shared レイ can be Rei for Ayanami and
Ray for Amuro. This script produces the FALLBACK -- a plain {jp: en} map
of every piece whose English is the same for everyone who bears it -- so
a record the override cannot resolve still gets its unambiguous pieces
swapped by content. Ambiguous pieces (レイ, アスカ, クラン...) are left out
here on purpose; only the override may decide those.

    python tools/name_pieces.py   -> translation/name_pieces.json
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
POOL = os.path.join(HERE, "..", "work", "patch_orig", "RPW_DATA.CPK")
OUT = os.path.join(HERE, "..", "translation", "name_pieces.json")
SEP = "・"          # ・


def split_japanese(jp, inpool):
    """The one split of a Japanese name whose halves both exist in the pool."""
    if len(jp) < 2:
        return None
    ks = [k for k in range(1, len(jp)) if inpool(jp[:k]) and inpool(jp[k:])]
    return ks[0] if len(ks) == 1 else None


def pieces_of(terms, inpool):
    """{piece_jp: piece_en} for every pilot term, plus the conflicts."""
    out, seen = {}, {}
    conflicts = set()
    for t in terms:
        jp, en = t["jp"], t["en"]
        if not en or (t.get("kind") or t.get("type")) != "pilot":
            continue
        pairs = []
        if SEP in jp:
            ps, toks = jp.split(SEP), en.split(" ")
            if len(ps) == len(toks) and all(ps):
                pairs = list(zip(ps, toks))
        else:
            toks = en.split(" ")
            k = split_japanese(jp, inpool) if len(toks) == 2 else None
            if k is not None:
                pairs = [(jp[:k], toks[1]), (jp[k:], toks[0])]      # surname, given
        for p, e in pairs:
            if p in seen and seen[p] != e:
                conflicts.add(p)
            seen.setdefault(p, e)
    for p, e in seen.items():
        if p not in conflicts:
            out[p] = e
    return out, sorted(conflicts)


def main():
    b = open(POOL, "rb").read()

    def inpool(s):
        try:
            return (b"\x00" + s.encode("cp932") + b"\x00") in b
        except Exception:
            return False

    gl = json.load(open(os.path.join(HERE, "..", "analysis", "glossary.json"), encoding="utf-8"))
    out, conflicts = pieces_of(gl["terms"], inpool)
    doc = {"_note": "Generated by tools/name_pieces.py: family / given name pieces whose "
                    "English is the same for everyone who bears them. Fallback for the "
                    "RPW swap; rpw.piece_overrides decides the shared ones per record. "
                    "Do not hand-edit.",
           "_conflicts_left_to_overrides": conflicts}
    doc.update(sorted(out.items()))
    json.dump(doc, open(OUT, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    print("%d unambiguous pieces; %d ambiguous left to piece_overrides: %s"
          % (len(out), len(conflicts), " ".join(conflicts)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
